Update images replacement

diff --git a/.github/workflows/ci-cd-hostinger.yml b/.github/workflows/ci-cd-hostinger.yml
--- a/.github/workflows/ci-cd-hostinger.yml
+++ b/.github/workflows/ci-cd-hostinger.yml
@@ -53,7 +53,9 @@ jobs:
           name: angular-dist
           path: dist
 
-      - name: Deploy via FTPS
+      - name: Deploy via FTPS (attempt 1)
+        id: deploy_attempt_1
+        continue-on-error: true
         uses: SamKirkland/FTP-Deploy-Action@v4.3.5
         with:
           # Accès FTP configurés dans :
@@ -67,3 +69,24 @@ jobs:
           local-dir: dist/
           server-dir: /public_html/portfolio/
           dangerous-clean-slate: true
+
+      - name: Deploy via FTPS (attempt 2 if needed)
+        id: deploy_attempt_2
+        if: steps.deploy_attempt_1.outcome == 'failure'
+        continue-on-error: true
+        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
+        with:
+          server: ${{ secrets.HOSTINGER_FTP_SERVER }}
+          username: ${{ secrets.HOSTINGER_FTP_USERNAME }}
+          password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
+          protocol: ftps
+          port: 21
+          local-dir: dist/
+          server-dir: /public_html/portfolio/
+          dangerous-clean-slate: true
+
+      - name: Fail if deployment attempts failed
+        if: steps.deploy_attempt_1.outcome == 'failure' && steps.deploy_attempt_2.outcome == 'failure'
+        run: |
+          echo "Deploy failed after 2 attempts."
+          exit 1
